### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by bessey** [saleswhale/schooling_rb#3]
Greetings Saleswhales! 

I am currently researching the use of Redis Streams in the Ruby community, with an interest in doing pretty much exactly what you're doing in this library. After some extensive Github searching, I've come to the conclusion that this library is one of few largely complete implementations of the full set of features described in https://redis.io/topics/streams-intro. You guys are state of the art!

Unfortunately, it has no license. Would you consider granting it MIT, as I see some of your other repos have that?

Sidenote, I would be interested to hear wether you use this in production and what your experience has been of it. If you fancy a chat, my email is in my GH profile.

**Comment by maxlorenz** [comment]
Hi Matt!

Thanks for having interest in our little gem. Yes, we created schooling due to the lack of feature-complete implementations. We will use MIT going forward!

This library is used in multiple Rails projects internally and is performing well so far. The speed is good but we haven't gotten close to a volume that would make Redis streams a bottleneck. I will add a few documents with our design decisions, feel free to open new issues!

**Comment by bessey** [comment]
Awseome, thank you!
